version: "3.3"
services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: myschema
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "127.0.0.1:3307:3306"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "127.0.0.1:15672:15672"

  api:
    build: ./api/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    restart: always


  frontend:
    build: ./frontend/
    ports:
      - "8081:8081"
    environment:
      api_base_url: "http://api:8080/"
    depends_on:
      - api


  receipt-service:
    build: ./receipt-service/
    environment:
      rabbitmq_host: "rabbitmq"
    depends_on:
      - rabbitmq
      - api
    restart: always